// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetPages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPages'](arg1, arg2, arg3, arg4);
}

export function GetTree(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTree'](arg1, arg2, arg3, arg4);
}
