// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig():Promise<{[key: string]: any}>;

export function GetPages(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<{[key: string]: any}>;

export function GetTree(arg1:string,arg2:string,arg3:string,arg4:string):Promise<{[key: string]: any}>;
